<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="CRUD_Operation.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
       <table>
               <tr>
                   <td>
                       <asp:Label ID="lblEnrollmentNo" runat="server" Text="Enter your EnrollmentNo:"></asp:Label>
                       <asp:TextBox ID="txtEnrollmentNo" runat="server"></asp:TextBox>
                   </td>
                </tr>

               <tr>
                    <td>
                        <asp:Label ID="lblStudentName" runat="server" Text="Enter your Student Name:"></asp:Label>
                        <asp:TextBox ID="txtStudentName" runat="server"></asp:TextBox>
                    </td>
               </tr>

               <tr>
                 <td>
                  <asp:Label ID="lblSemester" runat="server" Text="Enter your Semester:"></asp:Label>
                 <asp:TextBox ID="txtSemester" runat="server"></asp:TextBox>
              </td>
            </tr>

               <tr>
                 <td>
                  <asp:Label ID="lblSPI" runat="server" Text="Enter your SPI:"></asp:Label>
                 <asp:TextBox ID="txtSPI" runat="server"></asp:TextBox>
              </td>
            </tr>

              <tr>
                 <td>
                  <asp:Label ID="lblCPI" runat="server" Text="Enter your CPI:"></asp:Label>
                 <asp:TextBox ID="txtCPI" runat="server"></asp:TextBox>
              </td>
            </tr>

             <tr>
                 <td colspan="2">
                  <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click"/>
              </td>
            </tr>

           <tr>
               <td colspan="2">
                   <asp:GridView ID="grdData" runat="server" DataKeyNames="STU_ID" 
                       OnRowEditing="grdData_RowEditing" 
                       OnRowCancelingEdit="grdData_RowCancelingEdit" PageSize="3" 
                       AllowPaging="true" OnRowDeleting="grdData_RowDeleting" 
                       OnRowUpdating="grdData_RowUpdating" AutoGenerateDeleteButton="true" 
                       AutoGnerateEditButton="true" EmptyDataText="Please Enter data" 
                       OnPageIndexChanging="grdData_PageIndexChanging" 
                       AutoGenerateColumns="false">
                       <Columns>
                          <asp:TemplateField HeaderText="EnrollmentNo">
                            <ItemTemplate>
                                <asp:Label ID="l_lblEnrollmentNo" runat="server" Text='<%# Eval("EnrollmentNo") %>'></asp:Label>
                            </ItemTemplate>

                            <EditItemTemplate>
                                <asp:TextBox ID="t_lblEnrollmentNo" runat="server" Text='<%# Eval("EnrollmentNo") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>


                           <asp:TemplateField HeaderText="StudentName">
                                <ItemTemplate>
                                    <asp:Label ID="l_lblStudentName" runat="server" Text='<%#Eval("StudentName")%>'></asp:Label>
                                </ItemTemplate>

                                <EditItemTemplate>
                                    <asp:TextBox ID="t_lblStudentName" runat="server" Text='<%#Eval("StudentName")%>'></asp:TextBox>
                                </EditItemTemplate>
                            </asp:TemplateField>

                           <asp:TemplateField HeaderText="Semester">
                                 <ItemTemplate>
                                     <asp:Label ID="l_lblSemester" runat="server" Text='<%#Eval("Semester")%>'></asp:Label>
                                 </ItemTemplate>

                                 <EditItemTemplate>
                                     <asp:TextBox ID="t_lblSemester" runat="server" Text='<%#Eval("Semester")%>'></asp:TextBox>
                                 </EditItemTemplate>
                             </asp:TemplateField>

                           <asp:TemplateField HeaderText="SPI">
                              <ItemTemplate>
                                  <asp:Label ID="l_lblSPI" runat="server" Text='<%#Eval("SPI")%>'></asp:Label>
                              </ItemTemplate>

                              <EditItemTemplate>
                                  <asp:TextBox ID="t_lblSPI" runat="server" Text='<%#Eval("SPI")%>'></asp:TextBox>
                              </EditItemTemplate>
                          </asp:TemplateField>

                            <asp:TemplateField HeaderText="CPI">
                                <ItemTemplate>
                                    <asp:Label ID="l_lblCPI" runat="server" Text='<%#Eval("CPI")%>'></asp:Label>
                                </ItemTemplate>

                                <EditItemTemplate>
                                    <asp:TextBox ID="t_lblCPI" runat="server" Text='<%#Eval("CPI")%>'></asp:TextBox>
                                </EditItemTemplate>
                            </asp:TemplateField>

                       </Columns>
                   </asp:GridView>
               </td>
           </tr>

       </table>
    </form>
</body>
</html>
